In [1]:
import numpy as np
print("Hello My world")

Hello My world


In [2]:
a=np.array([[1,2,3],[8,4,9]])
b=np.array([[10,60,30],[20,40,50]])
print(a)


[[1 2 3]
 [8 4 9]]


In [3]:
print(b)

[[10 60 30]
 [20 40 50]]


In [5]:
#Horizontal stack
a1=np.hstack(a)
print(a1)

[1 2 3 8 4 9]


In [6]:
#verical stack
a2=np.vstack(a)
print(a2)

[[1 2 3]
 [8 4 9]]


In [7]:
a3=np.vstack((a,b))
print(a3)

[[ 1  2  3]
 [ 8  4  9]
 [10 60 30]
 [20 40 50]]


In [9]:
#range
a4=np.arange(1,11)
a4


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#Arange with step
f=np.arange(2,21,2)
f

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
#table of 13
a6=np.arange(13,131,13)
a6

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [14]:
#divide 1 to 5 in 10 part
a7=np.linspace(1.0,5.0,num=10)
a7

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
a[0:1]
a[0]

array([1, 2, 3])

In [17]:
a[1:2]

array([[8, 4, 9]])

In [19]:
#first array show
a[0]

array([1, 2, 3])

In [20]:
#second array show
a[1]

array([8, 4, 9])

In [21]:
a[1,0:]

array([8, 4, 9])

In [22]:
a[:,2]

array([3, 9])

In [29]:
#find second array in last element
a[1:2,2]

array([9])

In [27]:
#find first array in last element
a[0:1,2]

array([3])

In [30]:
b=np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
c=np.random.randint(0,10,size=(3,2))
c


array([[3, 3],
       [9, 0],
       [6, 5]])

In [33]:
d=np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#5 add in each element in array(broadcasting)
ar=np.array([1,2,3,4,5])
ar+=5
print(ar)

[ 6  7  8  9 10]


In [39]:
d=np.random.randint(0,10,size=(3,3))
print(c)
print(c.max())

[[3 3]
 [9 0]
 [6 5]]
9


In [40]:
d=np.random.randint(0,10,size=(3,3))
print(c)
print(c.sum())

[[3 3]
 [9 0]
 [6 5]]
26


In [42]:
d=np.random.randint(0,10,size=(3,3))
print(c)
print(c.min())

[[3 3]
 [9 0]
 [6 5]]
0


In [45]:
d=np.random.randint(0,10,size=(3,3))
print(c)
print(c.shape)
print("After reshape")
c=c.reshape(6,1)
print(c)

[[3 3]
 [9 0]
 [6 5]]
(3, 2)
After reshape
[[3]
 [3]
 [9]
 [0]
 [6]
 [5]]
